<#
.SYNOPSIS
    Builds the single ContextMenuEditor.ps1 from the source tree.

.DESCRIPTION
    Edit the files under scripts/, functions/, xaml/, config/ and native/, then run this to produce the
    single self-contained script that Launch.bat and the one-line launcher use. Order of the output:

      scripts/header.ps1          help block + param() (must come first)
      version, launch URL         $AppVersion / $AppLaunchUrl
      native/*.cs                 $NativeSource, $BridgeSource (C# compiled at runtime)
      config/*.json               $Config.<name> = (JSON) | ConvertFrom-Json
      scripts/start.ps1           assemblies, native types, state and constants
      functions/core/*.ps1        everything that works without a window (sorted by file name)
      library guard               -LibraryOnly stops here
      xaml/*.xaml                 $ResXaml, $MainXaml, $EditorXaml, $MessageXaml, $AboutXaml
      functions/ui/*.ps1          window helpers, views, dialogs
      scripts/main.ps1            build the window, wire events, show it

.PARAMETER LaunchUrl
    Where the compiled script is published (raw URL). Embedded so the one-line launch
    (irm <url> | iex) can relaunch itself elevated by downloading the script again.

.PARAMETER Version
    Shown in About. Defaults to the build date (yy.MM.dd); releases pass their tag without the v.

.PARAMETER Run
    Start the compiled editor when the build succeeds.
#>
param(
    [string]$LaunchUrl = '',
    [string]$Version = (Get-Date -Format 'yy.MM.dd'),
    [string]$Output = 'ContextMenuEditor.ps1',
    [switch]$Run
)
$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot

function Read-Source([string]$Rel) { return [IO.File]::ReadAllText((Join-Path $root $Rel)).TrimEnd() }

# Embeds text as a single-quoted here-string; a line starting with '@ would end it early.
function ConvertTo-HereString([string]$Var, [string]$Body, [string]$Source) {
    if ($Body -match "(?m)^'@") { throw "$Source has a line starting with '@, which would end its embedded here-string." }
    return "`$$Var = @'`r`n$Body`r`n'@"
}

$parts = [System.Collections.Generic.List[string]]::new()
$parts.Add((Read-Source 'scripts\header.ps1'))
$parts.Add("# Generated by Compile.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm') from scripts/, functions/, xaml/, config/ and native/.`r`n# Edit those files and recompile; changes made here are overwritten.")
$parts.Add("`$AppVersion = '$($Version.Replace("'", "''"))'`r`n`$AppLaunchUrl = '$($LaunchUrl.Replace("'", "''"))'")

$parts.Add((ConvertTo-HereString 'NativeSource' (Read-Source 'native\Native.cs') 'native\Native.cs'))
$parts.Add((ConvertTo-HereString 'BridgeSource' (Read-Source 'native\CmeSendTo.cs') 'native\CmeSendTo.cs'))

# Brand assets (assets\*.png / *.ico, built by tools\Build-Assets.ps1) as base64 strings.
# The 1024 px master is for the README only.
$parts.Add('$Assets = @{}')
foreach ($f in Get-ChildItem -LiteralPath (Join-Path $root 'assets') -File -ErrorAction SilentlyContinue | Where-Object { $_.Extension -in '.png', '.ico' -and $_.Name -notlike '*-1024.png' } | Sort-Object Name) {
    $parts.Add("`$Assets['$($f.Name)'] = '$([Convert]::ToBase64String([IO.File]::ReadAllBytes($f.FullName)))'")
}

$parts.Add('$Config = @{}')
foreach ($f in Get-ChildItem -LiteralPath (Join-Path $root 'config') -Filter *.json -ErrorAction SilentlyContinue | Sort-Object Name) {
    $json = [IO.File]::ReadAllText($f.FullName).TrimEnd()
    try { [void]($json | ConvertFrom-Json) } catch { throw "config\$($f.Name) is not valid JSON: $($_.Exception.Message)" }
    $parts.Add((ConvertTo-HereString "Config['$($f.BaseName)']" $json "config\$($f.Name)") + ' | ConvertFrom-Json')
}

$parts.Add((Read-Source 'scripts\start.ps1'))
foreach ($f in Get-ChildItem -LiteralPath (Join-Path $root 'functions\core') -Filter *.ps1 | Sort-Object Name) {
    $parts.Add((Read-Source "functions\core\$($f.Name)"))
}
$parts.Add('if ($LibraryOnly) { return }')

$xamlVars = [ordered]@{ 'resources.xaml' = 'ResXaml'; 'main.xaml' = 'MainXaml'; 'editor.xaml' = 'EditorXaml'; 'message.xaml' = 'MessageXaml'; 'about.xaml' = 'AboutXaml' }
foreach ($name in $xamlVars.Keys) {
    $text = Read-Source "xaml\$name"
    if ($name -ne 'resources.xaml') {
        try { [void][xml]($text.Replace('<!--RES-->', '')) } catch { throw "xaml\$name is not well-formed XML: $($_.Exception.Message)" }
    }
    $parts.Add((ConvertTo-HereString $xamlVars[$name] $text "xaml\$name"))
}

foreach ($f in Get-ChildItem -LiteralPath (Join-Path $root 'functions\ui') -Filter *.ps1 | Sort-Object Name) {
    $parts.Add((Read-Source "functions\ui\$($f.Name)"))
}
$parts.Add((Read-Source 'scripts\main.ps1'))

$script = ($parts -join "`r`n`r`n") + "`r`n"
$errors = $null
[void][System.Management.Automation.Language.Parser]::ParseInput($script, [ref]$null, [ref]$errors)
if ($errors) { throw "The compiled script does not parse: $($errors[0].Message) (line $($errors[0].Extent.StartLineNumber))" }

# Keep the output pure ASCII and write it without a BOM: "irm <url> | iex" passes a BOM through as code,
# which breaks parsing, and Windows PowerShell 5.1 reads BOM-less files as ANSI, which is only safe for ASCII.
$nonAscii = [regex]::Matches($script, '[^\x00-\x7F]')
if ($nonAscii.Count) {
    $line = ($script.Substring(0, $nonAscii[0].Index) -split "`n").Count
    throw "The compiled script has a non-ASCII character ('$($nonAscii[0].Value)') at line $line. Use an ASCII equivalent in the source file."
}
$outPath = Join-Path $root $Output
[IO.File]::WriteAllText($outPath, $script, [Text.UTF8Encoding]::new($false))
"Built ${Output}: $(($script -split "`n").Count) lines, $([math]::Round($script.Length / 1KB)) KB$(if ($LaunchUrl) { ", launch URL $LaunchUrl" })"

if ($Run) { & $outPath }
